// Generated by `tallpond typegen`. Do not edit by hand.
/* eslint-disable */
import type {} from '@tallpond/sdk'

export interface MemberNoteUpdatesRow {
  id: string
  updateId: string
  noteId: string
  payload: string
  createdAt: string
  updatedAt: string
}

export interface MemberNotesRow {
  id: string
  noteId: string
  title: string
  parentId: string
  deletedAt: number
  clientUpdatedAt: number
  createdAt: string
  updatedAt: string
}

export interface MemberPresenceRow {
  id: string
  presenceId: string
  noteId: string
  displayName: string
  data: unknown
  expiresAt: number
  createdAt: string
  updatedAt: string
}

export interface NoteUpdatesRow {
  id: string
  updateId: string
  noteId: string
  payload: string
  createdAt: string
  updatedAt: string
}

export interface NotesRow {
  id: string
  noteId: string
  title: string
  parentId: string
  deletedAt: number
  clientUpdatedAt: number
  createdAt: string
  updatedAt: string
}

declare module '@tallpond/sdk' {
  interface Register {
    tables: {
    member_note_updates: MemberNoteUpdatesRow
    member_notes: MemberNotesRow
    member_presence: MemberPresenceRow
    note_updates: NoteUpdatesRow
    notes: NotesRow
    }
  }
}
